apiVersion: apps/v1
kind: Deployment
metadata:
  name: unievent-deployment
  labels:nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: node-server
	image:amankothiyal/nodeapp:latest
	ports:
	- containerPort: 3000
